[tool.isort]
profile = "black"
line_length = 88
multi_line_output = 3
include_trailing_comma = true
force_sort_within_sections = true
known_first_party = ["app"]
force_single_line = true

[tool.black]
line-length = 88  # <-- 이거 반드시 맞춰
target-version = ['py311']
skip-string-normalization = true

[tool.flake8]
max-line-length = 88  # <-- 이것도 통일
