services:
  - type: web
    name: fast-api-sample
    runtime: docker  # ✅ 'env' → 'runtime'으로 수정
    plan: free
    region: oregon
    branch: main
    dockerfilePath: ./Dockerfile
    healthCheckPath: /docs
    autoDeploy: true
