services:
  - type: web
    name: fast-api-sample
    runtime: docker  # ← 이게 맞는 키
    plan: free
    region: oregon
    branch: main
    dockerfilePath: ./Dockerfile
    healthCheckPath: /docs
    autoDeploy: true
